[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-args=-Wl,--subsystem,windows"]

[alias]
xtask = "run --package xtask --release --"
c = "xwin clippy --target x86_64-pc-windows-msvc --all"
d = "xtask dist"
r = "xtask run"
